# netlify.toml

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Header Rules
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"
